# Get NMDS embeddings 

## Using Jamieson et al. (2015) algorithm

Algorithm taken from [https://github.com/kgjamieson/NEXT-psych/blob/master/next/apps/PoolBasedTripletMDS/algs/UncertaintySampling/utilsMDS.py](https://github.com/kgjamieson/NEXT-psych/blob/master/next/apps/PoolBasedTripletMDS/algs/UncertaintySampling/utilsMDS.py).

In [4]:
import numpy as np
import pandas
import utilsMDS as mds

## MWE 

In [21]:
N = 6
D = 2
S = list([[4,5,2],[1,2,3],[2,3,1],[4,2,5]])
mds.computeEmbedding(N, D, S)


(array([[  9.86735119e-01,   5.74802724e-01],
        [  6.34145764e-01,  -5.75616765e-01],
        [  9.19165933e-01,  -1.15261131e+00],
        [ -6.90451434e-01,  -1.52170016e-03],
        [  1.11247721e+00,  -8.25817644e-01],
        [ -3.82352591e-01,   3.28829987e+00]]), 0)

## Our data

In [11]:
df = pandas.read_csv('triplet_data.csv')
N = 16 # number of items
D = 2 # number of dimensions

### Get young embeddings

In [12]:
dyoung = df[df.age_group == "young"]

S_young =[]
for index, row in dyoung.iterrows():
     S_young.append([row["i"], row["j"], row["k"]])
    
len(S_young)

102

In [14]:
young_embed = mds.computeEmbedding(N, D, S_young)
young_embed[0]

array([[-0.52300326,  0.73709632],
       [ 0.17426272,  0.4067454 ],
       [ 0.35919134, -0.91664568],
       [ 0.51423239, -0.14775566],
       [-0.10093394, -0.40050238],
       [ 0.37722692, -1.06441414],
       [-0.10204416,  0.24901852],
       [ 0.55428386,  0.50852098],
       [-0.65716392, -0.64269408],
       [ 0.71024363,  0.27493634],
       [-0.28248701,  1.38525279],
       [ 1.03444536,  0.88420196],
       [-0.97273444, -0.39133958],
       [-0.11287879, -0.41067067],
       [-0.30824248,  1.07792189],
       [ 1.19545703, -0.04207195]])

###  Get mid embeddings

In [16]:
dmid = df[df.age_group == "mid"]
dmid = dmid[dmid.exp == 2]

S_mid =[]
for index, row in dmid.iterrows():
     S_mid.append([row["i"], row["j"], row["k"]])

mid_embed = mds.computeEmbedding(N, D, S_mid)
mid_embed[0]

array([[ 0.61461874,  0.76059518],
       [ 0.10420367, -0.85315334],
       [ 1.36640121, -0.19144397],
       [ 0.70535573,  0.05215367],
       [-0.4114543 ,  0.33652141],
       [ 0.54752126, -0.00292569],
       [ 0.07971522,  0.8504258 ],
       [-0.00732887,  0.90077926],
       [-0.98237938,  0.06910933],
       [ 1.06061432, -0.59306388],
       [-0.65394097, -0.17785315],
       [-0.22567121, -0.6981181 ],
       [-0.37777049, -1.06932592],
       [-0.36399429, -0.49892773],
       [ 0.1662656 , -1.08115869],
       [ 0.44412719, -1.15965725]])

Save for R

In [17]:
np.savetxt("mid_embed.csv", mid_embed[0], delimiter=",")